Reviews  - Star Rating
Husky-Helper/rfp2404-fec pull request #4
Opened 2024-06-08 08:48 UTC by Pallavi25Kishore

@mictro97 @shaoyuchen3213 
Pull request covers following functionalities - 
1. Have set up environment to run jest tests (please run npm install after pulling these changes in your local branch)
2. Have completed implementing functionality for displaying stars in the review tiles as per rating. 
3. Have added test suite for Star Rating component.

2024-06-08 17:48 UTC, Pallavi25Kishore commented
@shaoyuchen3213 @mictro97 
Adding commits 5, 6 and 7 to the pending pull request for 
1. Implementing createdAt date format feature and adding corresponding test
2. Implementing review summary feature and adding corresponding test

2024-06-10 18:37 UTC, mictro97 requested changes
Everything looks great! As nitpicks I would just change these few small things.

2024-06-10 18:37 UTC, mictro97 commented on client/src/components/Reviews/Modal.jsx
> +          <img className="modalImage" src={photo.url}></img>
I would consider adding alt text to the image tag if the image can't be displayed

2024-06-10 18:37 UTC, mictro97 commented on client/src/components/Reviews/ReviewBody.jsx
> +  const isValidUrl = (url) => {
Could put this function outside the component so it doesn't have to be recreated every render

2024-06-10 18:37 UTC, mictro97 commented on client/src/components/Reviews/ReviewTile.jsx
> +    <>
Maybe add a div here with a className to make styling easier

2024-06-10 18:51 UTC, Pallavi25Kishore commented on client/src/components/Reviews/ReviewTile.jsx
> +    <>
done, thanks for the suggestion :)

2024-06-10 18:52 UTC, Pallavi25Kishore commented on client/src/components/Reviews/Modal.jsx
> +          <img className="modalImage" src={photo.url}></img>
done :)

2024-06-10 18:53 UTC, Pallavi25Kishore commented on client/src/components/Reviews/ReviewBody.jsx
> +  const isValidUrl = (url) => {
sounds good, done :)

2024-06-10 18:54 UTC, mictro97 approved these changes
Looks good!

2024-06-10 18:54 UTC, merged